/*
 * $Copyright: (c) 2018 Broadcom Corp.
 * All Rights Reserved.$
 * File:     bm_ext_if.h
 * Purpose:  Behavior Model external structs
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated
 * Edits to this file will be lost when it is regenerated.
 *
 */

#ifndef _BM_EXT_IF_H_
#define _BM_EXT_IF_H_

#include "bm_enum.h"

/*
 * \brief Dynamic address information for physical table.
 *
 * The dynamic address information is passed along the register/memory
 * read/write functions to carry table index, port number, etc.
 */
typedef struct bm_pt_dyn_info_s {

    /*!
     * The index is the primary index if the table has more than a
     * single entry, i.e. memory-based tables and register arrays.
     */
    int index;

    /*
     * The table instance is used if more than one copy of a table
     * exists, for example a copy per-port, per-block or per-pipeline.
     * Use -1 to write all instances of this table.
     *
     * For port-based registers this value is the port number as used
     * in the current block type, i.e. physical port number for port
     * blocks, MMU port number for MMU blocks and logical port number
     * for other switching blocks.
     */
    int tbl_inst;

} bm_pt_dyn_info_t;

#endif /* _BM_EXT_IF_H_ */

