/*
 * $Copyright: (c) 2018 Broadcom Corp.
 * All Rights Reserved.$
 * File:     bm_enum.h
 * Purpose:  Behavior Model external structs
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated
 * Edits to this file will be lost when it is regenerated.
 *
 */

#ifndef _BM_ENUM_H_
#define _BM_ENUM_H_


typedef enum bm_sid_e {
    SOFTWARE_BLOCKMAP,
    SFC_EDB_PROFILEm = 1,
    SFC_IARB_PROFILEm = 2,
    SFC_MMU_PROFILEm = 3,
    PS_BIASm = 4,
    PS_BIAS_EXPm = 5,
    PS_EXPm = 6,
    PS_VALUEm = 7,
    PS_WORKER_BITSm = 8,
    PS_WORKER_COUNTm = 9,
    PS_WORKER_INIT_BITSm = 10,
    PS_WORKER_SIPm = 11,
    PS_WORKER_SMACm = 12,
    PS_WORKER_SPORTm = 13,
    TUPLE_Tm = 14,
    BCM_TBL_ENUM_COUNT = 15
} bm_sid_t;

#endif /* _BM_ENUM_H_ */

