/*
 * $Copyright: (c) 2018 Broadcom Corp.
 * All Rights Reserved.$
 * File:     bm_main.cpp
 * Purpose:  NPL Behavior Modeling Main Source
 *
 * DO NOT EDIT THIS FILE!
 * Edits to this file will be lost when it is regenerated.
 *
 */


/*
 * includes
 */

#include "bm_main.h"


/*
 * externs
 */

extern void bm_pt_init(void);
extern void bm_pt_free(void);

#ifdef BM_IN_TARGET_PP_TOP

/*
 * variables
 */

target_pp_top *bm_obj;


/*
 * function definitions
 */

void bm_ngsdk_init(target_pp_top *obj)
{
    bm_obj = obj;
    bm_pt_init();
}

void bm_ngsdk_free(void)
{
    bm_pt_free();
}

#else

/*
 * variables
 */

_BModel *bm_obj;


/*
 * function definitions
 */

void bm_ngsdk_init(_BModel *obj)
{
    bm_obj = obj;
    bm_pt_init();
}

void bm_ngsdk_free(void)
{
    bm_pt_free();
}

#endif /* BM_IN_TARGET_PP_TOP */

