/*
 * $Copyright: (c) 2018 Broadcom Corp.
 * All Rights Reserved.$
 * File:     bm_sfpt_if.c
 * Purpose:  Behavior Model sf physical table interface source
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated
 * Edits to this file will be lost when it is regenerated.
 *
 */

#include "include_libs.h"
#include "bm_field.h"
#include "bm_sfpt_if.h"
#include "bm_main.h"


int bm_sfpt_read(int unit, bm_sid_t sid,
               bm_pt_dyn_info_t *dyn_info, void *ovrr_info,
               uint32_t *data, size_t wsize)
{
    uint32_t field;
    uint64_t ref_value;
    uint index = dyn_info->index;

    assert(data);

    switch (sid) {

        default:
#ifndef NO_CONSOLE_OUTPUT
            bmi_log->error("ERROR: %s() Unknown table sid: 0x%x", __FUNCTION__, sid);
#endif
            return 1;
    }

    return 0;
}

int bm_sfpt_write(int unit, bm_sid_t sid,
                bm_pt_dyn_info_t *dyn_info, void *ovrr_info,
                uint32_t *data)
{
    uint32_t field;
    uint64_t ref_value;
    uint index = dyn_info->index;

    assert(data);

    switch (sid) {

        default:
#ifndef NO_CONSOLE_OUTPUT
            bmi_log->error("ERROR: %s() Unknown table sid: 0x%x", __FUNCTION__, sid);
#endif
            return 1;
    }

    return 0;
}
