/*
 * $Copyright: (c) 2018 Broadcom Corp.
 * All Rights Reserved.$
 * File:     bm_tbl_if.c
 * Purpose:  Behavior Model table interface source
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated
 * Edits to this file will be lost when it is regenerated.
 *
 */

#include "include_libs.h"
#include "bm_field.h"
#include "bm_tbl_if.h"
#include "bm_main.h"

/* load table entry pointers */
sfc_mmu_profile_entry_t *sfc_mmu_profile_loc_entry = NULL;
sfc_edb_profile_entry_t *sfc_edb_profile_loc_entry = NULL;
sfc_iarb_profile_entry_t *sfc_iarb_profile_loc_entry = NULL;
/* load struct entry pointers */

/* debug flag */
int debug_en = 0;


void bm_pt_init(void)
{
}

void bm_pt_free(void)
{
}

int bm_pt_read(int unit, bm_sid_t sid,
               bm_pt_dyn_info_t *dyn_info, void *ovrr_info,
               uint32_t *data, size_t wsize)
{
    uint32_t field;
    uint64_t ref_value;
    _64bits ref_addr;
    _1bit index1;
    int typ, status;
    int idx, size, high, low, start, end;

    assert(data);
    typ = *(int *) ovrr_info;
    status = 0;

    switch (sid) {

        case SFC_MMU_PROFILEm:
            if (bm_obj->sfc_mmu_profile->max_entries > (uint) dyn_info->index) {
                index1 = dyn_info->index;
                sfc_mmu_profile_loc_entry = bm_obj->sfc_mmu_profile->read_entry(&index1);
#ifndef NO_CONSOLE_OUTPUT
                if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                    sfc_mmu_profile_loc_entry->print();
                }
#endif
                sfc_mmu_profile_loc_entry->pack_data(data);
            } else {
                if (bm_obj->sfc_mmu_profile->max_entries != (uint) dyn_info->index) {
#ifndef NO_CONSOLE_OUTPUT
                    bmi_log->error("ERROR: %s(): Table sfc_mmu_profile, invalid index (%d)", __FUNCTION__, (uint) dyn_info->index);
#endif
                    return 1;
                } else if (typ == 3) {
                    sfc_mmu_profile_loc_entry = new sfc_mmu_profile_entry_t;
                    sfc_mmu_profile_loc_entry->unpack_data(data);
                    status = bm_obj->sfc_mmu_profile->lookup_entry(&sfc_mmu_profile_loc_entry);
#ifndef NO_CONSOLE_OUTPUT
                    if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                        sfc_mmu_profile_loc_entry->print();
                    }
#endif
                    sfc_mmu_profile_loc_entry->pack_data(data);
                    delete(sfc_mmu_profile_loc_entry);
                } else {
#ifndef NO_CONSOLE_OUTPUT
                    bmi_log->error("ERROR: %s(): Table sfc_mmu_profile, invalid operation (%d)", __FUNCTION__, typ);
#endif
                    return 1;
                }
            }
            break;

        case SFC_EDB_PROFILEm:
            if (bm_obj->sfc_edb_profile->max_entries > (uint) dyn_info->index) {
                index1 = dyn_info->index;
                sfc_edb_profile_loc_entry = bm_obj->sfc_edb_profile->read_entry(&index1);
#ifndef NO_CONSOLE_OUTPUT
                if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                    sfc_edb_profile_loc_entry->print();
                }
#endif
                sfc_edb_profile_loc_entry->pack_data(data);
            } else {
                if (bm_obj->sfc_edb_profile->max_entries != (uint) dyn_info->index) {
#ifndef NO_CONSOLE_OUTPUT
                    bmi_log->error("ERROR: %s(): Table sfc_edb_profile, invalid index (%d)", __FUNCTION__, (uint) dyn_info->index);
#endif
                    return 1;
                } else if (typ == 3) {
                    sfc_edb_profile_loc_entry = new sfc_edb_profile_entry_t;
                    sfc_edb_profile_loc_entry->unpack_data(data);
                    status = bm_obj->sfc_edb_profile->lookup_entry(&sfc_edb_profile_loc_entry);
#ifndef NO_CONSOLE_OUTPUT
                    if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                        sfc_edb_profile_loc_entry->print();
                    }
#endif
                    sfc_edb_profile_loc_entry->pack_data(data);
                    delete(sfc_edb_profile_loc_entry);
                } else {
#ifndef NO_CONSOLE_OUTPUT
                    bmi_log->error("ERROR: %s(): Table sfc_edb_profile, invalid operation (%d)", __FUNCTION__, typ);
#endif
                    return 1;
                }
            }
            break;

        case SFC_IARB_PROFILEm:
            if (bm_obj->sfc_iarb_profile->max_entries > (uint) dyn_info->index) {
                index1 = dyn_info->index;
                sfc_iarb_profile_loc_entry = bm_obj->sfc_iarb_profile->read_entry(&index1);
#ifndef NO_CONSOLE_OUTPUT
                if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                    sfc_iarb_profile_loc_entry->print();
                }
#endif
                sfc_iarb_profile_loc_entry->pack_data(data);
            } else {
                if (bm_obj->sfc_iarb_profile->max_entries != (uint) dyn_info->index) {
#ifndef NO_CONSOLE_OUTPUT
                    bmi_log->error("ERROR: %s(): Table sfc_iarb_profile, invalid index (%d)", __FUNCTION__, (uint) dyn_info->index);
#endif
                    return 1;
                } else if (typ == 3) {
                    sfc_iarb_profile_loc_entry = new sfc_iarb_profile_entry_t;
                    sfc_iarb_profile_loc_entry->unpack_data(data);
                    status = bm_obj->sfc_iarb_profile->lookup_entry(&sfc_iarb_profile_loc_entry);
#ifndef NO_CONSOLE_OUTPUT
                    if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                        sfc_iarb_profile_loc_entry->print();
                    }
#endif
                    sfc_iarb_profile_loc_entry->pack_data(data);
                    delete(sfc_iarb_profile_loc_entry);
                } else {
#ifndef NO_CONSOLE_OUTPUT
                    bmi_log->error("ERROR: %s(): Table sfc_iarb_profile, invalid operation (%d)", __FUNCTION__, typ);
#endif
                    return 1;
                }
            }
            break;

        case PS_BIASm:
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_bias:", __FUNCTION__);
                bm_obj->register_ps_bias->print();
            }
#endif
            field = (uint32_t)bm_obj->register_ps_bias->value0;
            bm_field_set(data, 0, 15, &field);
            field = (uint32_t)bm_obj->register_ps_bias->value1;
            bm_field_set(data, 16, 31, &field);
            field = (uint32_t)bm_obj->register_ps_bias->value2;
            bm_field_set(data, 32, 47, &field);
            field = (uint32_t)bm_obj->register_ps_bias->value3;
            bm_field_set(data, 48, 63, &field);
            break;

        case PS_BIAS_EXPm:
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_bias_exp:", __FUNCTION__);
                bm_obj->register_ps_bias_exp->print();
            }
#endif
            field = (uint32_t)bm_obj->register_ps_bias_exp->value0;
            bm_field_set(data, 0, 15, &field);
            field = (uint32_t)bm_obj->register_ps_bias_exp->value1;
            bm_field_set(data, 16, 31, &field);
            field = (uint32_t)bm_obj->register_ps_bias_exp->value2;
            bm_field_set(data, 32, 47, &field);
            field = (uint32_t)bm_obj->register_ps_bias_exp->value3;
            bm_field_set(data, 48, 63, &field);
            break;

        case PS_EXPm:
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_exp:", __FUNCTION__);
                bm_obj->register_ps_exp->print();
            }
#endif
            field = (uint32_t)bm_obj->register_ps_exp->value0;
            bm_field_set(data, 0, 15, &field);
            field = (uint32_t)bm_obj->register_ps_exp->value1;
            bm_field_set(data, 16, 31, &field);
            field = (uint32_t)bm_obj->register_ps_exp->value2;
            bm_field_set(data, 32, 47, &field);
            field = (uint32_t)bm_obj->register_ps_exp->value3;
            bm_field_set(data, 48, 63, &field);
            break;

        case PS_VALUEm:
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_value:", __FUNCTION__);
                bm_obj->register_ps_value->print();
            }
#endif
            size = 8192;
            start = 0;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                field = (uint32_t)bm_obj->register_ps_value->value00.range(high, low).to_int();
                bm_field_set(data, start, end, &field);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 8192;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                field = (uint32_t)bm_obj->register_ps_value->value01.range(high, low).to_int();
                bm_field_set(data, start, end, &field);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 16384;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                field = (uint32_t)bm_obj->register_ps_value->value10.range(high, low).to_int();
                bm_field_set(data, start, end, &field);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 24576;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                field = (uint32_t)bm_obj->register_ps_value->value11.range(high, low).to_int();
                bm_field_set(data, start, end, &field);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 32768;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                field = (uint32_t)bm_obj->register_ps_value->value20.range(high, low).to_int();
                bm_field_set(data, start, end, &field);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 40960;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                field = (uint32_t)bm_obj->register_ps_value->value21.range(high, low).to_int();
                bm_field_set(data, start, end, &field);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 49152;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                field = (uint32_t)bm_obj->register_ps_value->value30.range(high, low).to_int();
                bm_field_set(data, start, end, &field);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 57344;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                field = (uint32_t)bm_obj->register_ps_value->value31.range(high, low).to_int();
                bm_field_set(data, start, end, &field);
                start = end+1;
                low = high+1;
            }
            break;

        case PS_WORKER_BITSm:
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_worker_bits:", __FUNCTION__);
                bm_obj->register_ps_worker_bits->print();
            }
#endif
            field = (uint32_t)bm_obj->register_ps_worker_bits->value0;
            bm_field_set(data, 0, 15, &field);
            field = (uint32_t)bm_obj->register_ps_worker_bits->value1;
            bm_field_set(data, 16, 31, &field);
            field = (uint32_t)bm_obj->register_ps_worker_bits->value2;
            bm_field_set(data, 32, 47, &field);
            field = (uint32_t)bm_obj->register_ps_worker_bits->value3;
            bm_field_set(data, 48, 63, &field);
            break;

        case PS_WORKER_COUNTm:
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_worker_count:", __FUNCTION__);
                bm_obj->register_ps_worker_count->print();
            }
#endif
            field = (uint32_t)bm_obj->register_ps_worker_count->value0;
            bm_field_set(data, 0, 15, &field);
            field = (uint32_t)bm_obj->register_ps_worker_count->value1;
            bm_field_set(data, 16, 31, &field);
            field = (uint32_t)bm_obj->register_ps_worker_count->value2;
            bm_field_set(data, 32, 47, &field);
            field = (uint32_t)bm_obj->register_ps_worker_count->value3;
            bm_field_set(data, 48, 63, &field);
            break;

        case PS_WORKER_INIT_BITSm:
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_worker_init_bits:", __FUNCTION__);
                bm_obj->register_ps_worker_init_bits->print();
            }
#endif
            field = (uint32_t)bm_obj->register_ps_worker_init_bits->value0;
            bm_field_set(data, 0, 15, &field);
            field = (uint32_t)bm_obj->register_ps_worker_init_bits->value1;
            bm_field_set(data, 16, 31, &field);
            field = (uint32_t)bm_obj->register_ps_worker_init_bits->value2;
            bm_field_set(data, 32, 47, &field);
            field = (uint32_t)bm_obj->register_ps_worker_init_bits->value3;
            bm_field_set(data, 48, 63, &field);
            break;

        case PS_WORKER_SIPm:
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_worker_sip:", __FUNCTION__);
                bm_obj->register_ps_worker_sip->print();
            }
#endif
            field = (uint32_t)bm_obj->register_ps_worker_sip->value0;
            bm_field_set(data, 0, 31, &field);
            field = (uint32_t)bm_obj->register_ps_worker_sip->value1;
            bm_field_set(data, 32, 63, &field);
            field = (uint32_t)bm_obj->register_ps_worker_sip->value2;
            bm_field_set(data, 64, 95, &field);
            field = (uint32_t)bm_obj->register_ps_worker_sip->value3;
            bm_field_set(data, 96, 127, &field);
            break;

        case PS_WORKER_SMACm:
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_worker_smac:", __FUNCTION__);
                bm_obj->register_ps_worker_smac->print();
            }
#endif
            field = (uint32_t)bm_obj->register_ps_worker_smac->value0.range(31, 0);
            bm_field_set(data, 0, 31, &field);
            field = (uint32_t)bm_obj->register_ps_worker_smac->value0.range(47, 32);
            bm_field_set(data, 32, 47, &field);
            field = (uint32_t)bm_obj->register_ps_worker_smac->value1.range(31, 0);
            bm_field_set(data, 48, 79, &field);
            field = (uint32_t)bm_obj->register_ps_worker_smac->value1.range(47, 32);
            bm_field_set(data, 80, 95, &field);
            field = (uint32_t)bm_obj->register_ps_worker_smac->value2.range(31, 0);
            bm_field_set(data, 96, 127, &field);
            field = (uint32_t)bm_obj->register_ps_worker_smac->value2.range(47, 32);
            bm_field_set(data, 128, 143, &field);
            field = (uint32_t)bm_obj->register_ps_worker_smac->value3.range(31, 0);
            bm_field_set(data, 144, 175, &field);
            field = (uint32_t)bm_obj->register_ps_worker_smac->value3.range(47, 32);
            bm_field_set(data, 176, 191, &field);
            break;

        case PS_WORKER_SPORTm:
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_worker_sport:", __FUNCTION__);
                bm_obj->register_ps_worker_sport->print();
            }
#endif
            field = (uint32_t)bm_obj->register_ps_worker_sport->value0;
            bm_field_set(data, 0, 15, &field);
            field = (uint32_t)bm_obj->register_ps_worker_sport->value1;
            bm_field_set(data, 16, 31, &field);
            field = (uint32_t)bm_obj->register_ps_worker_sport->value2;
            bm_field_set(data, 32, 47, &field);
            field = (uint32_t)bm_obj->register_ps_worker_sport->value3;
            bm_field_set(data, 48, 63, &field);
            break;

        case TUPLE_Tm:
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_tuple_t:", __FUNCTION__);
                bm_obj->register_tuple_t->print();
            }
#endif
            field = (uint32_t)bm_obj->register_tuple_t->data_t;
            bm_field_set(data, 0, 31, &field);
            break;

        default:
#ifndef NO_CONSOLE_OUTPUT
            bmi_log->error("ERROR: %s() Unknown table sid: 0x%x", __FUNCTION__, sid);
#endif
            break;
    }

    return status;
}

int bm_pt_write(int unit, bm_sid_t sid,
                bm_pt_dyn_info_t *dyn_info, void *ovrr_info,
                uint32_t *data)
{
    uint32_t field;
    uint64_t ref_value;
    _64bits ref_addr;
    _1bit index1;
    int typ, status;
    int idx, size, high, low, start, end;

    assert(data);
    typ     = *(int *) ovrr_info;
    status  = 0;

    switch (sid) {

        case SFC_MMU_PROFILEm:
            if(bm_obj->sfc_mmu_profile->max_entries > (uint) dyn_info->index) {
                index1 = dyn_info->index;
                sfc_mmu_profile_loc_entry = bm_obj->sfc_mmu_profile->read_entry(&index1);
                sfc_mmu_profile_loc_entry->unpack_data(data);
                bm_obj->sfc_mmu_profile->write_entry(&index1, sfc_mmu_profile_loc_entry);
#ifndef NO_CONSOLE_OUTPUT
                if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                    sfc_mmu_profile_loc_entry->print();
                }
#endif
            } else {
                if (bm_obj->sfc_mmu_profile->max_entries != (uint) dyn_info->index) {
#ifndef NO_CONSOLE_OUTPUT
                    bmi_log->error("ERROR: %s(): Table sfc_mmu_profile, invalid index (%d)", __FUNCTION__, (uint) dyn_info->index);
#endif
                    return 1;
                }
                if ((typ != 0) && (typ != 2)) {
#ifndef NO_CONSOLE_OUTPUT
                    bmi_log->error("ERROR: %s(): Table sfc_mmu_profile, invalid operation (%d)", __FUNCTION__, typ);
#endif
                    return 1;
                }
                sfc_mmu_profile_loc_entry = new sfc_mmu_profile_entry_t;
                sfc_mmu_profile_loc_entry->unpack_data(data);
                if (typ == 0) {
                    status = bm_obj->sfc_mmu_profile->insert_entry(sfc_mmu_profile_loc_entry);
                } else if (typ == 2) {
                    status = bm_obj->sfc_mmu_profile->delete_entry(sfc_mmu_profile_loc_entry);
                }
#ifndef NO_CONSOLE_OUTPUT
                if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                    sfc_mmu_profile_loc_entry->print();
                }
#endif
                delete(sfc_mmu_profile_loc_entry);
            }
            break;

        case SFC_EDB_PROFILEm:
            if(bm_obj->sfc_edb_profile->max_entries > (uint) dyn_info->index) {
                index1 = dyn_info->index;
                sfc_edb_profile_loc_entry = bm_obj->sfc_edb_profile->read_entry(&index1);
                sfc_edb_profile_loc_entry->unpack_data(data);
                bm_obj->sfc_edb_profile->write_entry(&index1, sfc_edb_profile_loc_entry);
#ifndef NO_CONSOLE_OUTPUT
                if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                    sfc_edb_profile_loc_entry->print();
                }
#endif
            } else {
                if (bm_obj->sfc_edb_profile->max_entries != (uint) dyn_info->index) {
#ifndef NO_CONSOLE_OUTPUT
                    bmi_log->error("ERROR: %s(): Table sfc_edb_profile, invalid index (%d)", __FUNCTION__, (uint) dyn_info->index);
#endif
                    return 1;
                }
                if ((typ != 0) && (typ != 2)) {
#ifndef NO_CONSOLE_OUTPUT
                    bmi_log->error("ERROR: %s(): Table sfc_edb_profile, invalid operation (%d)", __FUNCTION__, typ);
#endif
                    return 1;
                }
                sfc_edb_profile_loc_entry = new sfc_edb_profile_entry_t;
                sfc_edb_profile_loc_entry->unpack_data(data);
                if (typ == 0) {
                    status = bm_obj->sfc_edb_profile->insert_entry(sfc_edb_profile_loc_entry);
                } else if (typ == 2) {
                    status = bm_obj->sfc_edb_profile->delete_entry(sfc_edb_profile_loc_entry);
                }
#ifndef NO_CONSOLE_OUTPUT
                if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                    sfc_edb_profile_loc_entry->print();
                }
#endif
                delete(sfc_edb_profile_loc_entry);
            }
            break;

        case SFC_IARB_PROFILEm:
            if(bm_obj->sfc_iarb_profile->max_entries > (uint) dyn_info->index) {
                index1 = dyn_info->index;
                sfc_iarb_profile_loc_entry = bm_obj->sfc_iarb_profile->read_entry(&index1);
                sfc_iarb_profile_loc_entry->unpack_data(data);
                bm_obj->sfc_iarb_profile->write_entry(&index1, sfc_iarb_profile_loc_entry);
#ifndef NO_CONSOLE_OUTPUT
                if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                    sfc_iarb_profile_loc_entry->print();
                }
#endif
            } else {
                if (bm_obj->sfc_iarb_profile->max_entries != (uint) dyn_info->index) {
#ifndef NO_CONSOLE_OUTPUT
                    bmi_log->error("ERROR: %s(): Table sfc_iarb_profile, invalid index (%d)", __FUNCTION__, (uint) dyn_info->index);
#endif
                    return 1;
                }
                if ((typ != 0) && (typ != 2)) {
#ifndef NO_CONSOLE_OUTPUT
                    bmi_log->error("ERROR: %s(): Table sfc_iarb_profile, invalid operation (%d)", __FUNCTION__, typ);
#endif
                    return 1;
                }
                sfc_iarb_profile_loc_entry = new sfc_iarb_profile_entry_t;
                sfc_iarb_profile_loc_entry->unpack_data(data);
                if (typ == 0) {
                    status = bm_obj->sfc_iarb_profile->insert_entry(sfc_iarb_profile_loc_entry);
                } else if (typ == 2) {
                    status = bm_obj->sfc_iarb_profile->delete_entry(sfc_iarb_profile_loc_entry);
                }
#ifndef NO_CONSOLE_OUTPUT
                if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                    sfc_iarb_profile_loc_entry->print();
                }
#endif
                delete(sfc_iarb_profile_loc_entry);
            }
            break;

        case PS_BIASm:
            bm_field_get(data, 0, 15, &field);
            bm_obj->register_ps_bias->set_value0((_16bits)field, -1, -1);
            bm_field_get(data, 16, 31, &field);
            bm_obj->register_ps_bias->set_value1((_16bits)field, -1, -1);
            bm_field_get(data, 32, 47, &field);
            bm_obj->register_ps_bias->set_value2((_16bits)field, -1, -1);
            bm_field_get(data, 48, 63, &field);
            bm_obj->register_ps_bias->set_value3((_16bits)field, -1, -1);
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_bias:", __FUNCTION__);
                bm_obj->register_ps_bias->print();
            }
#endif
            break;

        case PS_BIAS_EXPm:
            bm_field_get(data, 0, 15, &field);
            bm_obj->register_ps_bias_exp->set_value0((_16bits)field, -1, -1);
            bm_field_get(data, 16, 31, &field);
            bm_obj->register_ps_bias_exp->set_value1((_16bits)field, -1, -1);
            bm_field_get(data, 32, 47, &field);
            bm_obj->register_ps_bias_exp->set_value2((_16bits)field, -1, -1);
            bm_field_get(data, 48, 63, &field);
            bm_obj->register_ps_bias_exp->set_value3((_16bits)field, -1, -1);
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_bias_exp:", __FUNCTION__);
                bm_obj->register_ps_bias_exp->print();
            }
#endif
            break;

        case PS_EXPm:
            bm_field_get(data, 0, 15, &field);
            bm_obj->register_ps_exp->set_value0((_16bits)field, -1, -1);
            bm_field_get(data, 16, 31, &field);
            bm_obj->register_ps_exp->set_value1((_16bits)field, -1, -1);
            bm_field_get(data, 32, 47, &field);
            bm_obj->register_ps_exp->set_value2((_16bits)field, -1, -1);
            bm_field_get(data, 48, 63, &field);
            bm_obj->register_ps_exp->set_value3((_16bits)field, -1, -1);
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_exp:", __FUNCTION__);
                bm_obj->register_ps_exp->print();
            }
#endif
            break;

        case PS_VALUEm:
            size = 8192;
            start = 0;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                bm_field_get(data, start, end, &field);
                bm_obj->register_ps_value->set_value00((_8192bits)field, high, low);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 8192;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                bm_field_get(data, start, end, &field);
                bm_obj->register_ps_value->set_value01((_8192bits)field, high, low);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 16384;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                bm_field_get(data, start, end, &field);
                bm_obj->register_ps_value->set_value10((_8192bits)field, high, low);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 24576;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                bm_field_get(data, start, end, &field);
                bm_obj->register_ps_value->set_value11((_8192bits)field, high, low);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 32768;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                bm_field_get(data, start, end, &field);
                bm_obj->register_ps_value->set_value20((_8192bits)field, high, low);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 40960;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                bm_field_get(data, start, end, &field);
                bm_obj->register_ps_value->set_value21((_8192bits)field, high, low);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 49152;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                bm_field_get(data, start, end, &field);
                bm_obj->register_ps_value->set_value30((_8192bits)field, high, low);
                start = end+1;
                low = high+1;
            }
            size = 8192;
            start = 57344;
            low = 0;
            for (idx=0; idx<size; idx+=32) {
                if (size-idx < 32) {
                    end = start+size-idx-1;
                    high = low+size-idx-1;
                }
                else {
                    end = start+31;
                    high = low+31;
                }
                bm_field_get(data, start, end, &field);
                bm_obj->register_ps_value->set_value31((_8192bits)field, high, low);
                start = end+1;
                low = high+1;
            }
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_value:", __FUNCTION__);
                bm_obj->register_ps_value->print();
            }
#endif
            break;

        case PS_WORKER_BITSm:
            bm_field_get(data, 0, 15, &field);
            bm_obj->register_ps_worker_bits->set_value0((_16bits)field, -1, -1);
            bm_field_get(data, 16, 31, &field);
            bm_obj->register_ps_worker_bits->set_value1((_16bits)field, -1, -1);
            bm_field_get(data, 32, 47, &field);
            bm_obj->register_ps_worker_bits->set_value2((_16bits)field, -1, -1);
            bm_field_get(data, 48, 63, &field);
            bm_obj->register_ps_worker_bits->set_value3((_16bits)field, -1, -1);
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_worker_bits:", __FUNCTION__);
                bm_obj->register_ps_worker_bits->print();
            }
#endif
            break;

        case PS_WORKER_COUNTm:
            bm_field_get(data, 0, 15, &field);
            bm_obj->register_ps_worker_count->set_value0((_16bits)field, -1, -1);
            bm_field_get(data, 16, 31, &field);
            bm_obj->register_ps_worker_count->set_value1((_16bits)field, -1, -1);
            bm_field_get(data, 32, 47, &field);
            bm_obj->register_ps_worker_count->set_value2((_16bits)field, -1, -1);
            bm_field_get(data, 48, 63, &field);
            bm_obj->register_ps_worker_count->set_value3((_16bits)field, -1, -1);
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_worker_count:", __FUNCTION__);
                bm_obj->register_ps_worker_count->print();
            }
#endif
            break;

        case PS_WORKER_INIT_BITSm:
            bm_field_get(data, 0, 15, &field);
            bm_obj->register_ps_worker_init_bits->set_value0((_16bits)field, -1, -1);
            bm_field_get(data, 16, 31, &field);
            bm_obj->register_ps_worker_init_bits->set_value1((_16bits)field, -1, -1);
            bm_field_get(data, 32, 47, &field);
            bm_obj->register_ps_worker_init_bits->set_value2((_16bits)field, -1, -1);
            bm_field_get(data, 48, 63, &field);
            bm_obj->register_ps_worker_init_bits->set_value3((_16bits)field, -1, -1);
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_worker_init_bits:", __FUNCTION__);
                bm_obj->register_ps_worker_init_bits->print();
            }
#endif
            break;

        case PS_WORKER_SIPm:
            bm_field_get(data, 0, 31, &field);
            bm_obj->register_ps_worker_sip->set_value0((_32bits)field, -1, -1);
            bm_field_get(data, 32, 63, &field);
            bm_obj->register_ps_worker_sip->set_value1((_32bits)field, -1, -1);
            bm_field_get(data, 64, 95, &field);
            bm_obj->register_ps_worker_sip->set_value2((_32bits)field, -1, -1);
            bm_field_get(data, 96, 127, &field);
            bm_obj->register_ps_worker_sip->set_value3((_32bits)field, -1, -1);
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_worker_sip:", __FUNCTION__);
                bm_obj->register_ps_worker_sip->print();
            }
#endif
            break;

        case PS_WORKER_SMACm:
            bm_field_get(data, 0, 31, &field);
            bm_obj->register_ps_worker_smac->set_value0((_48bits)field, 31, 0);
            bm_field_get(data, 32, 47, &field);
            bm_obj->register_ps_worker_smac->set_value0((_48bits)field, 47, 32);
            bm_field_get(data, 48, 79, &field);
            bm_obj->register_ps_worker_smac->set_value1((_48bits)field, 31, 0);
            bm_field_get(data, 80, 95, &field);
            bm_obj->register_ps_worker_smac->set_value1((_48bits)field, 47, 32);
            bm_field_get(data, 96, 127, &field);
            bm_obj->register_ps_worker_smac->set_value2((_48bits)field, 31, 0);
            bm_field_get(data, 128, 143, &field);
            bm_obj->register_ps_worker_smac->set_value2((_48bits)field, 47, 32);
            bm_field_get(data, 144, 175, &field);
            bm_obj->register_ps_worker_smac->set_value3((_48bits)field, 31, 0);
            bm_field_get(data, 176, 191, &field);
            bm_obj->register_ps_worker_smac->set_value3((_48bits)field, 47, 32);
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_worker_smac:", __FUNCTION__);
                bm_obj->register_ps_worker_smac->print();
            }
#endif
            break;

        case PS_WORKER_SPORTm:
            bm_field_get(data, 0, 15, &field);
            bm_obj->register_ps_worker_sport->set_value0((_16bits)field, -1, -1);
            bm_field_get(data, 16, 31, &field);
            bm_obj->register_ps_worker_sport->set_value1((_16bits)field, -1, -1);
            bm_field_get(data, 32, 47, &field);
            bm_obj->register_ps_worker_sport->set_value2((_16bits)field, -1, -1);
            bm_field_get(data, 48, 63, &field);
            bm_obj->register_ps_worker_sport->set_value3((_16bits)field, -1, -1);
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_ps_worker_sport:", __FUNCTION__);
                bm_obj->register_ps_worker_sport->print();
            }
#endif
            break;

        case TUPLE_Tm:
            bm_field_get(data, 0, 31, &field);
            bm_obj->register_tuple_t->set_data_t((_32bits)field, -1, -1);
#ifndef NO_CONSOLE_OUTPUT
            if (bm_debug_lvl >= BM_DEBUG_LVL_DEBUG_NZ) {
                bmi_log->normal("%s(): register_tuple_t:", __FUNCTION__);
                bm_obj->register_tuple_t->print();
            }
#endif
            break;

        default:
#ifndef NO_CONSOLE_OUTPUT
            bmi_log->error("ERROR: %s() Unknown table sid: 0x%x", __FUNCTION__, sid);
#endif
            break;
    }

    return status;
}

void bm_lt_debug_enable(int en)
{
    debug_en = en;
}

int bm_lt_entry(int unit, bm_sid_t sid, bm_pt_dyn_info_t *dyn_info)
{
    _1bit index1;

    switch (sid) {

        case SFC_MMU_PROFILEm:
            index1 = dyn_info->index;
            sfc_mmu_profile_loc_entry = bm_obj->sfc_mmu_profile->read_entry(&index1);
#ifndef NO_CONSOLE_OUTPUT
            bmi_log->normal("%s(): sfc_mmu_profile[%d]:", __FUNCTION__, dyn_info->index);
            sfc_mmu_profile_loc_entry->print();
#endif
            break;

        case SFC_EDB_PROFILEm:
            index1 = dyn_info->index;
            sfc_edb_profile_loc_entry = bm_obj->sfc_edb_profile->read_entry(&index1);
#ifndef NO_CONSOLE_OUTPUT
            bmi_log->normal("%s(): sfc_edb_profile[%d]:", __FUNCTION__, dyn_info->index);
            sfc_edb_profile_loc_entry->print();
#endif
            break;

        case SFC_IARB_PROFILEm:
            index1 = dyn_info->index;
            sfc_iarb_profile_loc_entry = bm_obj->sfc_iarb_profile->read_entry(&index1);
#ifndef NO_CONSOLE_OUTPUT
            bmi_log->normal("%s(): sfc_iarb_profile[%d]:", __FUNCTION__, dyn_info->index);
            sfc_iarb_profile_loc_entry->print();
#endif
            break;

        default:
#ifndef NO_CONSOLE_OUTPUT
            bmi_log->error("ERROR: %s() Unknown table sid: 0x%x", __FUNCTION__, sid);
#endif
            break;
    }

    return 0;
}

